"""add_matrix_host_visibility

Revision ID: d516fa2eeebe
Revises: 19093464bc89
Create Date: 2026-04-07 17:06:18.169899
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd516fa2eeebe'
down_revision: Union[str, None] = '19093464bc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix_hosts', sa.Column('is_visible_to_players', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrix_hosts', 'is_visible_to_players')
    # ### end Alembic commands ###
