from datetime import datetime, date, UTC
from sqlalchemy import String, Text, Integer, Date, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base
from app.models.associations import log_characters, log_locations, log_organizations


class AdventureLog(Base):
    __tablename__ = "adventure_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    title: Mapped[str] = mapped_column(String(300))
    session_date: Mapped[date] = mapped_column(Date)
    run_number: Mapped[int | None] = mapped_column(Integer, default=None)

    objective: Mapped[str] = mapped_column(Text)
    result: Mapped[str] = mapped_column(Text)
    # success, partial_success, failure, critical_failure, abandoned
    outcome: Mapped[str | None] = mapped_column(String(50), default=None)

    payout: Mapped[str | None] = mapped_column(String(300), default=None)
    casualties: Mapped[str | None] = mapped_column(Text, default=None)

    # List of tag strings from the consequence taxonomy
    outcome_tags: Mapped[list] = mapped_column(JSON, default=list)

    # Consequence suggestions generated by the engine on save
    consequences_suggested: Mapped[list] = mapped_column(JSON, default=list)

    # GM-selected consequences being actively tracked
    consequences_active: Mapped[list] = mapped_column(JSON, default=list)

    # Party-level run heat (0-10)
    heat: Mapped[int] = mapped_column(Integer, default=0)
    # Ticks this run advances the campaign clock
    tick_count: Mapped[int] = mapped_column(Integer, default=1)
    # Name of the hiring party / employer
    employer: Mapped[str | None] = mapped_column(String(200), default=None)

    # World-state changes accepted/rejected at log creation time
    changes_applied: Mapped[list] = mapped_column(JSON, default=list)
    changes_excluded: Mapped[list] = mapped_column(JSON, default=list)

    gm_notes: Mapped[str | None] = mapped_column(Text, default=None)
    created_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(UTC))
    updated_at: Mapped[datetime] = mapped_column(
        default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC)
    )

    participants: Mapped[list["Character"]] = relationship(
        "Character", secondary=log_characters, back_populates="adventure_logs"
    )
    locations_involved: Mapped[list["Location"]] = relationship(
        "Location", secondary=log_locations, back_populates="adventure_logs"
    )
    orgs_involved: Mapped[list["Organization"]] = relationship(
        "Organization", secondary=log_organizations, back_populates="adventure_logs"
    )
