from datetime import datetime, date
from sqlalchemy import Column, Integer, String, Text, DateTime, Date, JSON
from sqlalchemy.orm import relationship
from app.db.base import Base
from app.models.associations import log_characters, log_locations, log_organizations


class AdventureLog(Base):
    __tablename__ = "adventure_logs"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(300), nullable=False)
    session_date = Column(Date, nullable=False)
    run_number = Column(Integer)

    objective = Column(Text, nullable=False)
    result = Column(Text, nullable=False)
    # success, partial_success, failure, critical_failure, abandoned
    outcome = Column(String(50))

    payout = Column(String(300))   # e.g. "¥45,000 + custom cyberware"
    casualties = Column(Text)      # Free-text: injuries, deaths, collateral

    # List of tag strings from the consequence taxonomy
    outcome_tags = Column(JSON, default=list)

    # Consequence suggestions generated by the engine on save (list of {tag, severity, suggestion})
    consequences_suggested = Column(JSON, default=list)

    # GM-selected consequences being actively tracked going forward
    consequences_active = Column(JSON, default=list)

    # Party-level run heat (0-10): avg heat delta per participant
    heat = Column(Integer, default=0)
    # Ticks this run advances the campaign clock (1 = normal session, 2-5 = downtime)
    tick_count = Column(Integer, default=1)
    # Name of the hiring party / employer as described in the narrative
    employer = Column(String(200))

    # World-state changes accepted/rejected at log creation time
    changes_applied  = Column(JSON, default=list)
    changes_excluded = Column(JSON, default=list)

    gm_notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    participants = relationship("Character", secondary=log_characters, back_populates="adventure_logs")
    locations_involved = relationship("Location", secondary=log_locations, back_populates="adventure_logs")
    orgs_involved = relationship("Organization", secondary=log_organizations, back_populates="adventure_logs")
